# Generated by Django 5.2.6 on 2025-09-19 04:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video_id', 'created_at'], name='fetchVideoA_video_i_7636ba_idx'), models.Index(fields=['operation', 'status'], name='fetchVideoA_operati_d84090_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('channel_title', models.CharField(max_length=254)),
                ('duration', models.CharField(max_length=20)),
                ('thumbnail_url', models.URLField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['video_id'], name='fetchVideoA_video_i_0892df_idx'), models.Index(fields=['channel_title'], name='fetchVideoA_channel_dc85fa_idx'), models.Index(fields=['created_at'], name='fetchVideoA_created_fbe3ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('quality', models.CharField(max_length=20)),
                ('format', models.CharField(default='mp4', max_length=10)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('download_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='fetchVideoApp.video')),
            ],
            options={
                'ordering': ['-download_time'],
                'indexes': [models.Index(fields=['video', 'download_time'], name='fetchVideoA_video_i_0b0ca3_idx'), models.Index(fields=['ip_address'], name='fetchVideoA_ip_addr_65d6c5_idx')],
            },
        ),
    ]
